# STABLE DIFFUSION EXPERIMENT CONFIGURATION
# This config file contains the experiment configuration for the Stable Diffusion img2img model from the diffusers library.


# IDENTIFIER CONFIGURATIONS
# Specifies the model and experiment identifiers.
# DO NOT CHANGE THESE!
model_identifier: img2img
exp_identifier: single-inference


# MODEL CONFIGURATIONS
# Specifies the model configurations.
model_id: YOUR DATA PATH/stable-diffusion-1-5  # Name of the Stable Diffusion repository on HuggingFace (e.g. stabilityai/stable-diffusion-2-1) or the path to the cloned repository (e.g. /mypath/stable-diffusion-2-1).
scheduler: DPMSolverMultistepScheduler  # Name of the scheduler algorithm.
att_slicing: True  # Whether attention slicing should be used (reduces memory consumption during the diffusion process at the cost of speed).
vae_slicing: True  # Whether VAE slicing should be used (reduces memory consumption during the decoding stage at the cost of speed).
vae_tiling: False  # Whether VAE tiling should be used (reduces memory consumption during the decoding stage at the cost of speed).
enable_xformers: False  # Whether to enable xFormers for optimized performance in the attention blocks (requires the xformers package).
gpu_id: 0  # GPU index.
diffusion_steps: 25  # Amount of diffusion steps to perform (higher values increase quality at the cost of speed).
guidance_scale: 9.5  # Guidance scale factor for classifier free guidance (higher values lead to better correspondence to the prompt, while lower values increase diversity).


# EXPERIMENT CONFIGURATIONS
# Specifies the experiment configurations.
output_path: YOUR DATA PATH/laion-5B/img_emb_1_5  # Path for storing the experiment results (a new folder will be placed at the specified location).
# PROMPT CONFIGURATION
# prompt:  kitchen kitchen tile backsplash ideas kitchens| # Input prompt where the positive part is separated from the negative part by a vertical line "|" without any whitespace in between.
load_prompt_embeds: None  # Path to a local file containing the prompt embeddings. Caution the parameter "prompt" does not apply, if a pre-generated prompt embedding is loaded from a file.
# LATENT NOISE & IMAGE CONFIGURATION
rand_seed: 42  # Random seed for sampling reproducible latent noise that is added to the input image and for sampling the encoded latents of the input image from the VAE.
height: 512  # Image height of the desired VAE output (used for resizing the input image and for computing the latent noise height).
width: 512  # Image width of the desired VAE output (used for resizing the input image and for computing the latent noise width).
images_per_prompt: 1  # Amount of images to generate per prompt (specifies the batch dimension of the latent noise).
load_latent_noise: None  # Path to a local file containing the latent noise tensor. Caution the parameters "height", "width" and "images_per_prompt" do not apply, if a pre-generated latent noise tensor is loaded from a file.
# image: ../../../data/jpk322/laion-5B/data/6766.jpg  # Path to a local image file.
strength: 0.8  # Specifies the degree to which the model should adjust the input image as a number between 0 and 1. The amount of diffusion steps, will be scaled by this number (diffusion_steps remains unchanged if strength set to 1).